# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 550)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #D8C7F3; /* Violeta pastel medio */\n"
"}\n"
"QStackedWidget {\n"
"    background-color: #EBD8FA; /* Violeta pastel más definido */\n"
"    border: 2px solid #C3A4E0; /* Borde violeta pastel más oscuro */\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"    color: #4A356E; /* Texto violeta más intenso */\n"
"    font-size: 16px;\n"
"    font-weight: bold; /* Resalta el texto */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_password = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(250, 320, 250, 30))
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.txt_company = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_company.setGeometry(QtCore.QRect(250, 200, 250, 30))
        self.txt_company.setObjectName("txt_company")
        self.txt_email = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(250, 260, 250, 30))
        self.txt_email.setObjectName("txt_email")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 200, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 260, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(80, 450, 171, 41))
        self.btn_login.setStyleSheet("QPushButton {\n"
"    background-color: #E1B7E7; /* Violeta pastel claro */\n"
"    color: #000000;            /* Texto negro */\n"
"    font-size: 16px;           /* Tamaño de letra */\n"
"    font-weight: bold;         /* Texto en negrita */\n"
"    border-radius: 5px;        /* Bordes redondeados */\n"
"    padding: 8px 12px;         /* Espaciado interno */\n"
"    border: 2px solid #B78CD7; /* Borde violeta más oscuro */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D39ED2; /* Fondo más oscuro al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #C383D1; /* Fondo aún más oscuro al presionar */\n"
"    border: 2px solid #9B69C0;  /* Cambio de borde al presionar */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F2E9F4; /* Fondo gris violáceo para botones desactivados */\n"
"    color: #A0A0A0;             /* Texto gris claro */\n"
"    border: 2px solid #D6C4D1;  /* Borde gris violáceo */\n"
"}\n"
"")
        self.btn_login.setObjectName("btn_login")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(300, 450, 171, 41))
        self.btn_register.setStyleSheet("QPushButton {\n"
"    background-color: #E1B7E7; /* Violeta pastel claro */\n"
"    color: #000000;            /* Texto negro */\n"
"    font-size: 16px;           /* Tamaño de letra */\n"
"    font-weight: bold;         /* Texto en negrita */\n"
"    border-radius: 5px;        /* Bordes redondeados */\n"
"    padding: 8px 12px;         /* Espaciado interno */\n"
"    border: 2px solid #B78CD7; /* Borde violeta más oscuro */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D39ED2; /* Fondo más oscuro al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #C383D1; /* Fondo aún más oscuro al presionar */\n"
"    border: 2px solid #9B69C0;  /* Cambio de borde al presionar */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F2E9F4; /* Fondo gris violáceo para botones desactivados */\n"
"    color: #A0A0A0;             /* Texto gris claro */\n"
"    border: 2px solid #D6C4D1;  /* Borde gris violáceo */\n"
"}\n"
"")
        self.btn_register.setObjectName("btn_register")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 380, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_password_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_password_2.setGeometry(QtCore.QRect(250, 380, 250, 30))
        self.txt_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password_2.setObjectName("txt_password_2")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(150, 10, 261, 161))
        self.logo_label.setObjectName("logo_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 579, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Empresa"))
        self.label_2.setText(_translate("MainWindow", "Contraseña"))
        self.label_3.setText(_translate("MainWindow", "Email"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.btn_register.setText(_translate("MainWindow", "Registrarse"))
        self.label_4.setText(_translate("MainWindow", "Repite contraseña"))
        self.logo_label.setText(_translate("MainWindow", "Logo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
